### ISSUE TITLE
[FEATURE]: <title> News & Updates section image changing proposal

### ISSUE THREAD

**Issue by hylcore-V** [koinos/koinos-io-website#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

![Screenshot_45](https://github.com/user-attachments/assets/b1dde8c1-1ead-4163-959c-752e48954802)
I think it makes sense to replace them with images of the same height.

**Comment by mvandeberg** [comment]
Thank you for this report. The images are coming directly from Medium and we used the wrong size image on the Medium post.
